// src/domain/standards/Nbr8995Database.ts

export interface NbrNorm {
    cat: string;
    room: string;
    lux: number;
    ugr: number | string;
    ra: number;
    plane: 'HP' | 'LP';
}

export const normsDatabase: NbrNorm[] =[
    { cat: "Áreas de Tráfego", room: "Áreas de circulação e corredores", lux: 100, ugr: 28, ra: 40, plane: 'LP' },
    { cat: "Áreas de Tráfego", room: "Escadas, escadas rolantes, esteiras", lux: 150, ugr: 25, ra: 40, plane: 'LP' },
    { cat: "Áreas de Tráfego", room: "Rampas de carregamento", lux: 150, ugr: 25, ra: 40, plane: 'LP' },
    { cat: "Edifícios (Geral)", room: "Cantinas", lux: 200, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Edifícios (Geral)", room: "Salas de descanso", lux: 100, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Edifícios (Geral)", room: "Salas de exercícios físicos", lux: 300, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Edifícios (Geral)", room: "Vestiários, banheiros, toaletes", lux: 200, ugr: 25, ra: 80, plane: 'LP' },
    { cat: "Edifícios (Geral)", room: "Sala de primeiros socorros", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Edifícios (Geral)", room: "Salas para atendimento médico", lux: 500, ugr: 16, ra: 90, plane: 'HP' },
    { cat: "Edifícios (Geral)", room: "Salas de controle de instalações", lux: 150, ugr: 25, ra: 60, plane: 'HP' },
    { cat: "Indústria", room: "Armazenamento (Depósitos)", lux: 100, ugr: 25, ra: 60, plane: 'LP' },
    { cat: "Indústria", room: "Expedição e embalagem", lux: 300, ugr: 25, ra: 60, plane: 'HP' },
    { cat: "Indústria (Alim.)", room: "Preparação de alimentos", lux: 500, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Indústria (Alim.)", room: "Inspeção de cor", lux: 1000, ugr: 19, ra: 90, plane: 'HP' },
    { cat: "Indústria (Metal)", room: "Forjamento (livre)", lux: 200, ugr: 25, ra: 60, plane: 'HP' },
    { cat: "Indústria (Metal)", room: "Soldagem", lux: 300, ugr: 22, ra: 60, plane: 'HP' },
    { cat: "Indústria (Metal)", room: "Usinagem grosseira", lux: 300, ugr: 22, ra: 60, plane: 'HP' },
    { cat: "Indústria (Metal)", room: "Usinagem média", lux: 500, ugr: 22, ra: 60, plane: 'HP' },
    { cat: "Indústria (Metal)", room: "Usinagem fina", lux: 750, ugr: 19, ra: 60, plane: 'HP' },
    { cat: "Indústria (Eletr.)", room: "Montagem de componentes (Geral)", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Indústria (Eletr.)", room: "Montagem fina / Inspeção", lux: 1000, ugr: 16, ra: 80, plane: 'HP' },
    { cat: "Indústria (Textil)", room: "Costura fina", lux: 750, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Indústria (Gráfica)", room: "Impressão à máquina", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Indústria (Gráfica)", room: "Inspeção de cores (Controle)", lux: 1500, ugr: 16, ra: 90, plane: 'HP' },
    { cat: "Indústria (Madeira)", room: "Marcenaria (bancada)", lux: 300, ugr: 22, ra: 60, plane: 'HP' },
    { cat: "Indústria (Madeira)", room: "Acabamento / Pintura", lux: 750, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Escritório", room: "Arquivamento, cópia, circulação", lux: 300, ugr: 25, ra: 80, plane: 'LP' },
    { cat: "Escritório", room: "Escrita, digitação, leitura", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Escritório", room: "Desenho técnico", lux: 750, ugr: 16, ra: 80, plane: 'HP' },
    { cat: "Escritório", room: "Estações de trabalho CAD", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Escritório", room: "Salas de conferência / reunião", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Escritório", room: "Recepção / Balcão", lux: 300, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Varejo", room: "Área de vendas (pequenas lojas)", lux: 300, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Varejo", room: "Área de vendas (grandes lojas)", lux: 500, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Varejo", room: "Caixa / Empacotamento", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Varejo", room: "Vitrine (Destaque)", lux: 1000, ugr: "-", ra: 80, plane: 'HP' },
    { cat: "Locais Públicos", room: "Saguões de entrada", lux: 100, ugr: 22, ra: 60, plane: 'LP' },
    { cat: "Locais Públicos", room: "Bilheterias", lux: 300, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Locais Públicos", room: "Restaurantes (Salão)", lux: 200, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Locais Públicos", room: "Restaurantes (Cozinha)", lux: 500, ugr: 22, ra: 80, plane: 'HP' },
    { cat: "Locais Públicos", room: "Teatros / Cinemas (Foyer)", lux: 200, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Locais Públicos", room: "Museus (Exposição geral)", lux: 300, ugr: 19, ra: 80, plane: 'LP' },
    { cat: "Locais Públicos", room: "Bibliotecas (Estantes)", lux: 200, ugr: 19, ra: 80, plane: 'LP' },
    { cat: "Locais Públicos", room: "Bibliotecas (Leitura)", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Locais Públicos", room: "Estacionamento Coberto", lux: 75, ugr: 25, ra: 40, plane: 'LP' },
    { cat: "Educação", room: "Sala de aula", lux: 300, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Sala de aula (Noturno/Adultos)", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Quadro negro (Vertical)", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Auditório / Anfiteatro", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Laboratórios", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Salas de arte / desenho", lux: 500, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Educação", room: "Ginásios esportivos", lux: 300, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Saúde", room: "Salas de espera", lux: 200, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Saúde", room: "Corredores (dia)", lux: 200, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Saúde", room: "Enfermaria (Geral)", lux: 100, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Saúde", room: "Enfermaria (Exame simples)", lux: 300, ugr: 19, ra: 80, plane: 'HP' },
    { cat: "Saúde", room: "Exame e tratamento (Geral)", lux: 1000, ugr: 19, ra: 90, plane: 'HP' },
    { cat: "Saúde", room: "Salas de cirurgia (Geral)", lux: 1000, ugr: 19, ra: 90, plane: 'HP' },
    { cat: "Saúde", room: "Salas de cirurgia (Cavidade)", lux: 10000, ugr: "-", ra: 90, plane: 'HP' },
    { cat: "Saúde", room: "Dentista (Iluminação geral)", lux: 500, ugr: 19, ra: 90, plane: 'HP' },
    { cat: "Saúde", room: "Dentista (No paciente)", lux: 1000, ugr: "-", ra: 90, plane: 'HP' },
    { cat: "Transporte", room: "Aeroportos (Embarque/Check-in)", lux: 500, ugr: 19, ra: 80, plane: 'LP' },
    { cat: "Transporte", room: "Aeroportos (Saguões)", lux: 200, ugr: 22, ra: 80, plane: 'LP' },
    { cat: "Transporte", room: "Estações ferroviárias (Plataforma)", lux: 50, ugr: 28, ra: 40, plane: 'LP' }
]; 